### ISSUE TITLE
Remove Command Bus in favor of Pipeline

### ISSUE THREAD

**Issue by joselfonseca** [joselfonseca/laravel-api#17]
Removing the command bus for the installation in favor of the Laravel Pipeline class is an option to remove a dependency.

**Comment by joselfonseca** [comment]
Fixed here https://github.com/joselfonseca/laravel-api/releases/tag/3.1.0

**Comment by kslimani** [comment]
@joselfonseca : this ticket is closed, but just wanted to notice a "minor code cleaning miss" : you forgot also to remove the `laravel-tactician.php` file in config folder.

**Comment by joselfonseca** [comment]
Thanks! Will delete it for the next release.

https://github.com/joselfonseca/laravel-api/issues/19
